// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserRegisteryNET.Data;

#nullable disable

namespace UserRegisteryNET.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250227204307_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("UserRegisteryNET.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            LastName = "lastName1",
                            Name = "name1",
                            Password = "password_1_123",
                            TCKN = "12345678911"
                        },
                        new
                        {
                            UserId = 2,
                            LastName = "lastName2",
                            Name = "name2",
                            Password = "password_2_123",
                            TCKN = "12345678912"
                        },
                        new
                        {
                            UserId = 3,
                            LastName = "lastName3",
                            Name = "name3",
                            Password = "password_3_123",
                            TCKN = "12345678913"
                        },
                        new
                        {
                            UserId = 4,
                            LastName = "lastName4",
                            Name = "name4",
                            Password = "password_4_123",
                            TCKN = "12345678914"
                        },
                        new
                        {
                            UserId = 5,
                            LastName = "lastName5",
                            Name = "name5",
                            Password = "password_5_123",
                            TCKN = "12345678915"
                        },
                        new
                        {
                            UserId = 6,
                            LastName = "lastName6",
                            Name = "name6",
                            Password = "password_6_123",
                            TCKN = "12345678916"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
