const API_BASE_URL_DEVELOPMENT = "https://localhost:7255";
const API_BASE_URL_PRODUCTION = "https://appname.azurewebsites.net"; // For cloud

const ENDPOINTS = {
    GET_ALL_USERS: 'get-all-users',
    GET_USER_BY_ID: 'get-user-by-id',
    GET_USER_BY_TCKN: 'get-user-by-tckn',
    CREATE_USER: 'create-user',
    UPDATE_USER: 'update-user',
    DELETE_USER_BY_ID: 'delete-user-by-id',
    DELETE_USER_BY_TCKN: 'delete-user-by-tckn'
};

const development = {
    API_URL_GET_ALL_USERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_GET_USER_BY_TCKN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_TCKN}`,
    API_URL_CREATE_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_USER}`,
    API_URL_UPDATE_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER_BY_ID}`,
    API_URL_DELETE_USER_BY_TCKN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER_BY_TCKN}`
};

const production = {
    API_URL_GET_ALL_USERS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_GET_USER_BY_TCKN: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USER_BY_TCKN}`,
    API_URL_CREATE_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_USER}`,
    API_URL_UPDATE_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_USER_BY_ID}`,
    API_URL_DELETE_USER_BY_TCKN: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_USER_BY_TCKN}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
